### ISSUE TITLE
Wrong path for node_module/generator-jhipster

### ISSUE THREAD

**Issue by GuiF007** [bastienmichaux/generator-jhipster-db-helper#53] opened 2018-04-02 21:07 UTC
##### **Overview of the issue**

WIth a fresh install of jHipster (4.14.1) and Node last LTS (8.11), impossible to run the `yo jhipster-db-helper`.

```
➜  MyProject git:(master) ✗ yo jhipster-db-helper
module.js:540
    throw err;
    ^

Error: Cannot find module '../node_modules/generator-jhipster/generators/generator-constants.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/MyUser/Documents/workspace/MyProject/node_modules/generator-jhipster-db-helper/generators/dbh.js:2:27)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

##### **Suggest a Fix**

In the `MyProject/node_modules/generator-jhipster-db-helper/generators/dbh.js` file, I fixed like this. And it works like a charm ! Maybe I missed something ?

```
const jhipsterConstants = require('../../../node_modules/generator-jhipster/generators/generator-constants.js');
const jhipsterCore = require('jhipster-core');
const jhipsterModuleSubgenerator = require('../../../node_modules/generator-jhipster/generators/modules/index.js');
```

I just fixed path of the two lines "node_modules".

##### **JHipster & JHipster-db-helper Version(s)**

jHipster 4.14.1
jHipster-db-helper 1.0.0

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.my.project",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "MyProject",
    "packageName": "com.my.project",
    "packageFolder": "com/my/project",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "6a5725a72ac8998832e6989ba5da3bf4a5e2d452",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}
```
---
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment] 2018-04-02 21:09
It could be similar to jhipster/generator-jhipster#7353

**Comment by GuiF007** [comment] 2018-04-02 21:11
It's exactly this ! I had the same error message when I ran the script jhipster:entity.

**Comment by gmarziou** [comment] 2018-04-02 21:28
In the other issue, the problem comes from mixing globally installed module with locally installed jhipster.

**Comment by dcaravana** [comment] 2018-04-19 15:50
This may be helpful here: it (apparently) works with JHipster v5.0.0-beta.0 (I mean it doesn't give this error or any other one but I didn't go further).

**Comment by GuiF007** [comment] 2018-04-19 22:32
Hum... I will check that later :) Thanks for the info 👍

**Comment by bastienmichaux** [comment] 2018-04-20 12:28
I'll look at this. Thanks for mentioning the JHipster version. We've already used them in the past for testing our module against various configs.

Also sorry for the lack of work on this module. Life being what it is, we lack time for keeping up with the past and current JHipster versions.

**Comment by AdrienHorgnies** [comment] 2018-05-04 16:57
@GuiF007 I just updated to 1.1.0. While I didn't work on this particular issue, a lot of things changed. Can you confirm you still have the issue ?

**Comment by GuiF007** [comment] 2018-05-06 13:06
Well, with jHipster 5.0.0-beta.1, I don't have anymore this problem, but the hook does not fire...

**Comment by GuiF007** [comment] 2018-05-06 19:17
Both generators are installed globally yes. But it's still painful to use yeoman and yarn...

**Comment by AdrienHorgnies** [comment] 2018-05-09 13:26
Well, the more reliable way is to install both locally. I just wanted to know to reproduce the error. I can't work on this atm though.

**Comment by alessandro-aglietti** [comment] 2018-09-06 22:04
Thank you very much @GuiF007! 
I still got errors because the
`../../../node_modules/generator-jhipster/generators/modules/index.js` is not there prior to [this](https://github.com/jhipster/generator-jhipster/commit/70283fbf10c9d569954ccc083a32c1dacc3d3923) :(

I have tried to change the import path to
`../../../node_modules/generator-jhipster/generators/generator-base.js`
but I still got **Could not add jhipster module configuration**

Any suggestions?

**Comment by ecostanzi** [comment] 2019-03-13 21:14
I just tried with jhipster 5.8.2. It seems to be working by removing the `'../`' and by using `generators/generator-base.js` instead of `modules/index.js`:
```javascript
const jhipsterConstants = require('generator-jhipster/generators/generator-constants.js');
...
const jhipsterModuleSubgenerator = require('generator-jhipster/generators/generator-base.js');
```
Both the module and generator-jhipster are in the node_modules of  the project.

**Comment by AdrienHorgnies** [comment] 2019-03-14 13:31
@ecostanzi Try it without further compatibility code to see what Travis CI will say.

**Comment by ecostanzi** [comment] 2019-03-14 18:40
@AdrienHorgnies Thanks. Generation seems to be working. Backend tests are failing, I'll look into it.

**Comment by mabliedana** [comment] 2019-05-24 10:24
With Jhipster v6.0.1, I have fixed by doing these changes:

1) Edit file node_modules/generator-jhipster-db-helper/generators/dbh.js

Change line:
const jhipsterModuleSubgenerator = require ('...

by
const jhipsterModuleSubgenerator = require('../../../node_modules/generator-jhipster/generators/entity/index.js');
(Because in jHipster >5.0.2 generators/modules/index.js has been replaced with generators/entity/index.js)

2) Edit files generators\app\index.js and generators\fix-entity\index.js:

Change line :
this.jhipsterAppConfig = this.getJhipsterAppConfig();

by
this.jhipsterAppConfig = this.getAllJhipsterConfig();

**Comment by mhmdanish** [comment] 2019-05-27 04:43
can you explain it simply

**Comment by AdrienHorgnies** [comment] 2019-05-27 09:11
@mabliedana If you have a fix, can you do a PR ? I'll be happy to do a review.

**Comment by AdrienHorgnies** [comment] 2019-05-27 09:13
I just noticed I didn't make a release with last merge, do you have the issue using the last merge ? (git clone, cd & yarn  .)

**Comment by end-user** [comment] 2020-03-11 12:44
FWIW, I also am having this issue on a fresh install against jhipster v6.8.0

**Comment by AdrienHorgnies** [comment] 2020-03-11 15:02
@bastienmichaux Can you look into this or maybe ask GSC to assign someone ?

**Comment by igortregub** [comment] 2020-06-05 09:50
Is there any chance to fix this issue?

**Comment by WiteCastle** [comment] 2020-06-05 13:08
@AdrienHorgnies I just started a pull request with the fixes by @mabliedana.

**Comment by AdrienHorgnies** [comment] 2020-06-10 10:04
@WiteCastle 
Hi, unfortunately I'm not interested in maintaining this project, I don't work with Jhipster anymore.
I contacted CTO from my previous company which ordered that project. He'll see with @bastienmichaux what he can do to ensure this project is well maintained.
I'll keep you updated.

**Comment by AdrienHorgnies** [comment] 2020-06-17 11:22
No news yet... Let's move forward with the PR #64 anyway.

**Closed** 2020-06-20 16:30 UTC
